fix: various bug fixes and improvements on ci publish jobs

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -50,8 +50,8 @@ jobs:
 
       - name: Set TARGET_SDK in env
         run: |
-          pip3 install -r packages/utils/yaml_get/requirements.txt
-          export GET_BIN=packages/utils/yaml_get/yaml_get.py
+          pip3 install -r packages/utils/manifest_get/requirements.txt
+          export GET_BIN=packages/utils/manifest_get/manifest_get.py
           export GET_KEY=global.android.target_sdk_version
           echo "##[set-env name=TARGET_SDK;]$($GET_BIN $GET_KEY)"
 
@@ -96,10 +96,10 @@ jobs:
           name: build-${{ github.run_id }}
           path: packages/build
 
-      - name: Set TARGET_SDK
+      - name: Set TARGET_SDK in env
         run: |
-          pip3 install -r packages/utils/yaml_get/requirements.txt
-          export GET_BIN=packages/utils/yaml_get/yaml_get.py
+          pip3 install -r packages/utils/manifest_get/requirements.txt
+          export GET_BIN=packages/utils/manifest_get/manifest_get.py
           export GET_KEY=global.android.target_sdk_version
           echo "##[set-env name=TARGET_SDK;]$($GET_BIN $GET_KEY)"
 
@@ -149,18 +149,41 @@ jobs:
           name: build-${{ github.run_id }}
           path: packages/build
 
+      - name: Set simulator destination in env
+        working-directory: ios/Bridge
+        run:
+          DESTINATION=$(
+            xcodebuild -showdestinations
+              -project GomobileIPFS.xcodeproj
+              -scheme GomobileIPFS
+            | awk '/Ineligible destinations for/ {exit} {print}'
+            | grep 'platform:iOS Simulator'
+            | awk -F 'id:' '{print $2}'
+            | cut -d',' -f1
+            | tail -n1
+          );
+          if [ -z "$DESTINATION" ]; then
+            echo "::error::No compatible simulator found to run the test"
+            exit 1;
+          fi;
+          echo "##[set-env name=DESTINATION;]$DESTINATION"
+
       - name: Run iOS Bridge tests
         working-directory: ios/Bridge
         run:
-          xcodebuild test -project GomobileIPFS.xcodeproj
-          -scheme GomobileIPFS -sdk iphonesimulator
-          -destination "platform=iOS Simulator,name=iPhone 11,OS=13.3"
+          xcodebuild test
+            -project GomobileIPFS.xcodeproj
+            -scheme GomobileIPFS
+            -sdk iphonesimulator
+            -destination "platform=iOS Simulator,id=$DESTINATION"
 
       - name: Build iOS Bridge
-        working-directory: ios/Bridge
+        working-directory: packages
         run:
-          xcodebuild -project GomobileIPFS.xcodeproj
-          -scheme GomobileIPFS -sdk iphonesimulator
-          -destination "platform=iOS Simulator,name=iPhone 11,OS=13.3" &&
-          pip3 install -r ../../packages/utils/cocoapod_format/requirements.txt
-          && ../../packages/utils/cocoapod_format/cocoapod_format_bridge.py
+          xcodebuild
+            -project ../ios/Bridge/GomobileIPFS.xcodeproj
+            -scheme GomobileIPFS
+            -sdk iphonesimulator
+            -destination "platform=iOS Simulator,id=$DESTINATION"
+          && pip3 install -r utils/cocoapod_format/requirements.txt
+          && utils/cocoapod_format/cocoapod_format_bridge.py
diff --git a/packages/Makefile b/packages/Makefile
--- a/packages/Makefile
+++ b/packages/Makefile
@@ -1,6 +1,9 @@
 MAKEFILE_DIR = $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
 MANIFEST_FILE = $(MAKEFILE_DIR)/Manifest.yml
+
 UTILS_DIR = $(MAKEFILE_DIR)/utils
+UTIL_MANIFEST_GET_BIN = $(UTILS_DIR)/manifest_get/manifest_get.sh
+UTIL_MANIFEST_GET = $(UTILS_DIR)/manifest_get
 UTIL_MAVEN_FORMAT = $(UTILS_DIR)/maven_format
 UTIL_MAVEN_FORMAT_REQ = $(UTIL_MAVEN_FORMAT)/requirements.txt
 UTIL_MAVEN_FORMAT_CORE_BIN = $(UTIL_MAVEN_FORMAT)/maven_format_core.py
@@ -18,9 +21,15 @@ UTIL_COCOAPOD_PUBLISH_CORE_BIN = $(UTIL_COCOAPOD_PUBLISH)/cocoapod_publish_core.
 BUILD_DIR = $(MAKEFILE_DIR)/build
 PIP = pip3
 
+MANIFEST_GET_FUNC=$(or $(shell $(UTIL_MANIFEST_GET_BIN) $(1)),$(error "Can't get <$(1)> from Manifest.yml"))
+DEV_VERSION := 0.0.42-dev
+VERSION := $(or $(GOMOBILE_IPFS_VERSION),$(DEV_VERSION))
+ANDROID_GROUP_ID := $(shell echo $(call MANIFEST_GET_FUNC,global.group_id) | tr . /)
+ANDROID_CORE_ARTIFACT_ID := $(call MANIFEST_GET_FUNC,go_core.android.artifact_id)
+
 GO_DIR = $(MAKEFILE_DIR)/../go
-GO_SRC = $(shell find $(GO_DIR) -not \( -path $(GO_DIR)/vendor -prune \) -name \*.go)
 GO_VENDOR = $(GO_DIR)/vendor
+GO_SRC = $(shell find $(GO_DIR) -not \( -path $(GO_VENDOR) -prune \) -name \*.go)
 GO_MOD_FILES = $(GO_DIR)/go.mod $(GO_DIR)/go.sum
 
 CORE_PACKAGE = github.com/ipfs-shipyard/gomobile-ipfs/go/bind/core
@@ -33,15 +42,17 @@ ANDROID_DIR = $(MAKEFILE_DIR)/../android
 ANDROID_BUILD_DIR = $(BUILD_DIR)/android
 ANDROID_BUILD_DIR_INT = $(ANDROID_BUILD_DIR)/intermediates
 ANDROID_BUILD_DIR_INT_CORE = $(ANDROID_BUILD_DIR_INT)/core
-ANDROID_BUILD_DIR_MAV = $(ANDROID_BUILD_DIR)/maven
 ANDROID_CORE = $(ANDROID_BUILD_DIR_INT_CORE)/core.aar
+ANDROID_BUILD_DIR_MAV = $(ANDROID_BUILD_DIR)/maven
+ANDROID_BUILD_DIR_MAV_CORE = $(ANDROID_BUILD_DIR_MAV)/$(ANDROID_GROUP_ID)/$(ANDROID_CORE_ARTIFACT_ID)/$(VERSION)
 
 IOS_DIR = $(MAKEFILE_DIR)/../ios
 IOS_BUILD_DIR = $(BUILD_DIR)/ios
 IOS_BUILD_DIR_INT = $(IOS_BUILD_DIR)/intermediates
 IOS_BUILD_DIR_INT_CORE = $(IOS_BUILD_DIR_INT)/core
-IOS_BUILD_DIR_CCP = $(IOS_BUILD_DIR)/cocoapods
 IOS_CORE = $(IOS_BUILD_DIR_INT_CORE)/Core.framework
+IOS_BUILD_DIR_CCP = $(IOS_BUILD_DIR)/cocoapods
+IOS_BUILD_DIR_CCP_CORE = $(IOS_BUILD_DIR_CCP)/$(IOS_CORE_PACKAGE)/$(VERSION)
 
 DOC_DIR = $(MAKEFILE_DIR)/../docs
 ANDROID_DOC_DIR = $(DOC_DIR)/android
@@ -52,21 +63,26 @@ IOS_DOC_DIR = $(DOC_DIR)/ios
 
 help:
 	@echo 'Commands:'
-	@$(MAKE) -pRrq -f $(lastword $(MAKEFILE_LIST)) : 2>/dev/null | awk -v RS= -F: '/^# File/,/^# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' | sort | egrep -v -e '^[^[:alnum:]]' -e '^$@$$' | grep -v / | sed 's/^/	$(HELP_MSG_PREFIX)make /'
+	@$(MAKE) -pRrq -f $(lastword $(MAKEFILE_LIST)) : 2>/dev/null \
+		| awk -v RS= -F: '/^# File/,/^# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' \
+		| sort \
+		| egrep -v -e '^[^[:alnum:]]' -e '^$@$$' \
+		| grep -v / \
+		| sed 's/^/	$(HELP_MSG_PREFIX)make /'
 
-# Build core rules
+# Build rules
 build_core: build_core.android build_core.ios
 
-build_core.android: $(ANDROID_BUILD_DIR_MAV)
+build_core.android: $(ANDROID_BUILD_DIR_MAV_CORE)
 
-$(ANDROID_BUILD_DIR_MAV): $(ANDROID_CORE) $(MANIFEST_FILE)
+$(ANDROID_BUILD_DIR_MAV_CORE): $(ANDROID_CORE) $(MANIFEST_FILE)
 	@echo '------------------------------------'
 	@echo '   Android Core: Maven formatting   '
 	@echo '------------------------------------'
 	@if [ "$$($(PIP) freeze | grep -f $(UTIL_MAVEN_FORMAT_REQ) | wc -l)" != "$$(wc -l < $(UTIL_MAVEN_FORMAT_REQ))" ]; then \
 		echo 'Installing pip dependencies:'; $(PIP) install -r $(UTIL_MAVEN_FORMAT_REQ); echo; \
 	fi
-	@$(UTIL_MAVEN_FORMAT_CORE_BIN) && touch $(ANDROID_BUILD_DIR_MAV)
+	@$(UTIL_MAVEN_FORMAT_CORE_BIN) && touch $(ANDROID_BUILD_DIR_MAV_CORE)
 	@echo 'Done!'
 
 $(ANDROID_CORE): $(ANDROID_BUILD_DIR_INT_CORE) $(GO_SRC) $(GO_VENDOR) | $(GOMOBILE)
@@ -79,16 +95,16 @@ $(ANDROID_CORE): $(ANDROID_BUILD_DIR_INT_CORE) $(GO_SRC) $(GO_VENDOR) | $(GOMOBI
 $(ANDROID_BUILD_DIR_INT_CORE):
 	@mkdir -p $(ANDROID_BUILD_DIR_INT_CORE)
 
-build_core.ios: $(IOS_BUILD_DIR_CCP)
+build_core.ios: $(IOS_BUILD_DIR_CCP_CORE)
 
-$(IOS_BUILD_DIR_CCP): $(IOS_CORE) $(MANIFEST_FILE)
+$(IOS_BUILD_DIR_CCP_CORE): $(IOS_CORE) $(MANIFEST_FILE)
 	@echo '------------------------------------'
 	@echo '   iOS Core: CocoaPod formatting   '
 	@echo '------------------------------------'
 	@if [ "$$($(PIP) freeze | grep -f $(UTIL_COCOAPOD_FORMAT_REQ) | wc -l)" != "$$(wc -l < $(UTIL_COCOAPOD_FORMAT_REQ))" ]; then \
 		echo 'Installing pip dependencies:'; $(PIP) install -r $(UTIL_COCOAPOD_FORMAT_REQ); echo; \
 	fi
-	@$(UTIL_COCOAPOD_FORMAT_CORE_BIN) && touch $(IOS_BUILD_DIR_CCP)
+	@$(UTIL_COCOAPOD_FORMAT_CORE_BIN) && touch $(IOS_BUILD_DIR_CCP_CORE)
 	@echo 'Done!'
 
 $(IOS_CORE): $(IOS_BUILD_DIR_INT_CORE) $(GO_SRC) $(GO_VENDOR) | $(GOMOBILE)
@@ -106,7 +122,7 @@ publish: publish_core publish_bridge
 
 publish_core: publish_core.android publish_core.ios
 
-publish_core.android: build_core.android
+publish_core.android: fail_on_dev build_core.android
 	@echo '------------------------------------'
 	@echo '   Android Core: Maven publishing   '
 	@echo '------------------------------------'
@@ -116,7 +132,7 @@ publish_core.android: build_core.android
 	@$(UTIL_MAVEN_PUBLISH_CORE_BIN)
 	@echo 'Done!'
 
-publish_core.ios: build_core.ios
+publish_core.ios: fail_on_dev build_core.ios
 	@echo '------------------------------------'
 	@echo '   iOS Core: CocoaPod publishing   '
 	@echo '------------------------------------'
@@ -128,17 +144,14 @@ publish_core.ios: build_core.ios
 
 publish_bridge: publish_bridge.android publish_bridge.ios
 
-publish_bridge.android:
+publish_bridge.android: fail_on_dev build_core.android
 	@echo '------------------------------------'
 	@echo '  Android Bridge: Maven publishing  '
 	@echo '------------------------------------'
-	@if [ "$$($(PIP) freeze | grep -f $(UTIL_MAVEN_FORMAT_REQ) -f $(UTIL_MAVEN_PUBLISH_REQ) | wc -l)" != "$$(cat $(UTIL_MAVEN_FORMAT_REQ) $(UTIL_MAVEN_PUBLISH_REQ) | sort | uniq | wc -l )" ]; then \
-		echo 'Installing pip dependencies:'; $(PIP) install -r $(UTIL_MAVEN_FORMAT_REQ) -r $(UTIL_MAVEN_PUBLISH_REQ); echo; \
-	fi
 	@cd $(ANDROID_DIR) && ./gradlew bridge:bintrayUpload
 	@echo 'Done!'
 
-publish_bridge.ios:
+publish_bridge.ios: fail_on_dev build_core.ios
 	@echo '------------------------------------'
 	@echo '  iOS Bridge: CocoaPod publishing   '
 	@echo '------------------------------------'
@@ -178,6 +191,7 @@ docgen.ios: $(IOS_DOC_DIR) build_core.ios
 $(IOS_DOC_DIR):
 	@mkdir -p $(IOS_DOC_DIR)
 
+# Test rules
 test: test_core test_bridge
 
 test_bridge: test_bridge.android test_bridge.ios
@@ -217,6 +231,7 @@ test_core: $(GO_VENDOR)
 	@cd $(GO_DIR) && go test -v ./...
 	@echo 'Done!'
 
+# Misc rules
 $(GOMOBILE):
 	@echo '------------------------------------'
 	@echo '      Go: installing Gomobile       '
@@ -231,6 +246,12 @@ $(GO_VENDOR): $(GO_MOD_FILES)
 	@echo '------------------------------------'
 	@cd $(GO_DIR) && GO111MODULE=on go mod vendor
 	@echo 'Done!'
+
+fail_on_dev:
+	@if [ "$(VERSION)" == "$(DEV_VERSION)" ]; then \
+		>&2 echo "Can't publish a dev version: GOMOBILE_IPFS_VERSION env variable not set";	\
+		exit 1; \
+	fi
 
 # Clean rules
 clean: clean.android clean.ios
